openapi: 3.0.3
info:
  title: Phone API
  version: 1.0.0
  description: Endpoints to retrieve phone information.
paths:
  /phone/:
    get:
      operationId: phone_retrieve
      tags:
      - phone
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
